export { default as Bloodpressure } from './Bloodpressure';
export { default as Bloodsugar } from './Bloodsugar';
export { default as Exercise } from './Exercise';
export { default as Foods } from './Foods';
export { default as Insulin } from './Insulin';
export { default as Stressandhappy } from './Stressandhappy';
export { default as Todayjob } from './Todayjob';
export { default as Treatment } from './Treatment';
export { default as Weight } from './Weight';
